# Generated by Django 5.2 on 2025-04-17 16:43

from django.db import migrations, models

#Me estoy volviendo loco
#locoooo

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.SmallIntegerField()),
                ('disponible', models.BooleanField()),
                ('imagen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
